### ISSUE TITLE
Missing Build

### ISSUE THREAD

**Issue by collapsedwave** [roots/roots-sass#31]
Gruntfile is missing a build task in this repo

**Comment by kalenjohnson** [comment]
It is?

https://github.com/roots/roots-sass/blob/master/Gruntfile.js#L164

**Comment by collapsedwave** [comment]
Weird. Does Yeoman pull down an outdated version of the repo if I fetch master?

**Comment by kalenjohnson** [comment]
I don't follow. Yeoman is not used on this project.

**Comment by collapsedwave** [comment]
Sorry, I should have been more specific. Yo wordpress > selecting roots/roots-sass master branch pulls down a Gruntfile without the build task... No idea, but my bad.

**Comment by JulienMelissas** [comment]
We should clarify and say "Yeoman is not _currently_ being used on this project" :wink: 
That said, yeah the issue with that is probably in the yo wordpress generator, not here.
